backup:
  retention_days: 7
binaries:
  primary_binary: finalvudatasim
  supported_binaries:
  - vuDataSim
  - RakvuDataSim
  - finalvudatasim
  - gvudatsim
eps:
  default_unique_key: 1
  max_unique_key: 1000000000
logging:
  log_backup_count: 5
  log_file: node-manager.log
  log_max_size: 10485760
network:
  remote_host: 127.0.0.1
  remote_user: vunet
  streamlit_address: 0.0.0.0
  streamlit_port: 8501
paths:
  local_backups_dir: backups
  local_logs_dir: logs
  remote_binary_dir: /home/vunet/vuDataSim/vuDataSim/bin/
  remote_ssh_key: ~/.ssh/id_rsa
process:
  default_timeout: 300
  graceful_shutdown_timeout: 10
  remote_timeout: 300
clickhouse:
  host: "10.32.3.50"
  port: 9000
  database: "vusmart"
  username: "monitoring_read"
  password: "StrongP@assword123"
monitoring_db:
  host: "10.32.3.50"
  port: 9000
  database: "monitoring"
  username: "monitoring_read"
  password: "StrongP@assword123"
monitored_pods:
  - "linuxmonitor-8d545644d-wv77v"
  - "apache-metrics-6d7f45d5d8-vbmcf"
  - "mssql-telegraf-pipeline-dcffcd5f6-kqmch"
  - "apache-metrics-6d7f45d5d8-gdzlv"
monitored_nodes:
  - "164.52.214.212"
  - "164.52.214.184"
  - "164.52.214.134"
  - "164.52.213.234"
  - "164.52.213.181"
  - "164.52.213.158"
  - "216.48.191.10"