cluster_settings:
    backup_retention_days: 30
    conflict_resolution: manual
    connection_timeout: 10
    max_retries: 3
    sync_timeout: 60
nodes:
    Prod-184:
        host: 164.52.214.184
        user: vunet
        key_path: ~/.ssh/id_rsa
        conf_dir: /home/vunet/Oct_13
        binary_dir: /home/vunet/Oct_13/bin
        metrics_port: 0
        description: /home/vunet/Oct_13
        enabled: true
