cluster_settings:
    backup_retention_days: 30
    conflict_resolution: manual
    connection_timeout: 10
    max_retries: 3
    sync_timeout: 60
nodes:
    prod 11:
        host: 164.52.214.184
        user: vunet
        key_path: ~/.ssh/id_rsa
        conf_dir: /home/vunet/Oct13
        binary_dir: /home/vunet/Oct13/bin
        metrics_port: 0
        description: /home/vunet/Oct13
        enabled: true
    localhost:
        host: localhost
        user: vunet
        key_path: ~/.ssh/id_rsa
        conf_dir: /tmp/local_metrics
        binary_dir: /tmp/local_metrics
        metrics_port: 0
        description: Local Node Metrics API
        enabled: true
