cluster_settings:
    backup_retention_days: 30
    conflict_resolution: manual
    connection_timeout: 10
    max_retries: 3
    sync_timeout: 60
nodes:
    184_Testing:
        host: 164.52.214.184
        user: vunet
        key_path: ~/.ssh/id_rsa
        conf_dir: /home/vunet/NEWTESTING
        binary_dir: /home/vunet/NEWTESTING
        description: ""
        enabled: true
    e2e-108-10:
        host: 216.48.191.10
        user: vunet
        key_path: ~/.ssh/id_rsa
        conf_dir: /home/vunet/vuDataSim/vuDataSim/conf.d
        binary_dir: /home/vunet/vuDataSim/vuDataSim/bin
        description: Primary vuDataSim node
        enabled: true
